service: service1

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev

functions:
  get:
    handler: handler.main
    events:
      - http: GET /

